name: Build and Push Docker Image

on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'
  workflow_dispatch:    # 添加手动触发按钮

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get current date and time
        id: date
        run: echo "DATE_TAG=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/subconverter-self:${{ env.DATE_TAG }}
            ${{ secrets.DOCKER_USERNAME }}/subconverter-self:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
